language: node_js
node_js:
- 6
script: true
after_success: npm run coverage
deploy:
  provider: npm
  email: chuck7liu@gmail.com
  api_key:
    secure: HI25qoa36l80ZJNKchETxSO2Bh1QQ0/LOohCDd1IMUpXE4Wa1mvFaTSs81rQojQxFlQJqhvVf3S9Vi7MdfDRpya8h6PoSlX8BbYVL7TT4vN43X47YhPCbGA6QYfM7AibfC/YDKsImrWfcQTNPND9rvio5Y38Z62EQ4Bl1dkDrr2439xgddhBV3xFcBofR35y0VjxgftpX3qCLBSRAMqU2iYJZURDCYvmrtSddXjF2tJOHp9NeC/N5RdBhXs81xCZw0nyEcthGoUH8I78dAhO2ZHKqZgEPxoDowEyEIsK/RI9Gzr6nmj7hCFUGaXmpzS0RYufRNDKUPUVYkCkNESuBzsvtkERAdbqP4W2T8A81Bc7b9ft/Xw2YfYnF8HE9S5vh0h/YWoaAF947QnDazRVB/IICMMij/AXkYyLtj5AK89oIVVMX7rM2YBtzOhrOYZXYJC3S2Rya5D+NMXmZ2FfP85PokPQ74YowhAF5Il7dR/g1+rBq+gjnJbum8AQgCkUr5+mO40xi5wHN9fLDPD3Ca0BF7PqL7yisFOFyZlu1KQ73WC6r1mepaIf4LjOMRYod8ZKg6SIncw0Us9O+KE9D8Cd8b/f9Dp7aMmuIHoZktyliO5mVvualhfP4ukNKGMAyup8QyyGIv65MDLxfrcbRtzYDSqpviSb8Ksa4lohg0o=
  on:
    tags: true
